-- =============================================================================
-- SYSAVA - SCHEMA ENXUTO PARA UM NOVO PROJETO SUPABASE (21 TABELAS)
-- =============================================================================
-- Auditoria: docs/AUDITORIA_BANCO.md
--
-- Inclui apenas as tabelas usadas pelo portal Streamlit e pelos
-- sincronizadores (audit_backup / class_registry / grade_semanal /
-- student_attendance / sync_lessons / duplicate_checker / supabase_monitor).
--
-- NAO inclui as 13 tabelas de automacao (ficam no SQLite escola_ativa.db):
--   student_grades, blocked_dates, aula_sequence_map, planejamento_config,
--   turma_disciplina_config, discipline_aliases, registration_queue, settings,
--   qualitative_points, grade_milestones, user_reminders, user_profiles,
--   student_scores.
--
-- Como usar:
--   1. Crie um novo projeto no Supabase (plano free).
--   2. Abra o SQL Editor e cole TODO este arquivo. Execute.
--   3. Coloque URL e chave anon do novo projeto em .streamlit/secrets.toml.
--   4. Rode o restore: python scripts/restore_new_supabase.py
--
-- Idempotente: pode ser executado mais de uma vez.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS unaccent;

-- -----------------------------------------------------------------------------
-- 1. Usuarios e estrutura academica
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_users (
    username  TEXT PRIMARY KEY,
    password  TEXT NOT NULL,
    name      TEXT NOT NULL,
    ra        TEXT UNIQUE,
    role      TEXT DEFAULT 'student',
    status    TEXT DEFAULT 'active',
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.schools (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    gre  TEXT
);

CREATE TABLE IF NOT EXISTS public.classes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    portal_name   TEXT,
    code          TEXT UNIQUE NOT NULL,
    school_id     BIGINT REFERENCES public.schools(id),
    official_name TEXT,
    tipo_turma    TEXT,
    ano_letivo    TEXT
);

CREATE TABLE IF NOT EXISTS public.subjects (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT UNIQUE NOT NULL,
    type             TEXT NOT NULL DEFAULT 'regular',
    duration_type    TEXT DEFAULT 'mensal',
    max_hours        INTEGER DEFAULT 40,
    lessons_per_week INTEGER DEFAULT 8,
    group_type       TEXT DEFAULT 'semana',
    folder_name      TEXT,
    carga_horaria    INTEGER,
    status           TEXT DEFAULT 'active',
    aliases          JSONB NOT NULL DEFAULT '[]'::jsonb,
    aliases_id       BIGINT REFERENCES public.subjects(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.class_subjects (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id   BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
    is_active  BOOLEAN DEFAULT true,
    CONSTRAINT class_subjects_class_subject_unique UNIQUE (class_id, subject_id)
);

CREATE TABLE IF NOT EXISTS public.student_enrollments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username TEXT REFERENCES public.app_users(username) ON DELETE CASCADE,
    class_id      BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
    CONSTRAINT student_enrollments_user_class_unique UNIQUE (user_username, class_id)
);

-- -----------------------------------------------------------------------------
-- 2. Conteudo de ensino
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lessons (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        TEXT NOT NULL,
    description  TEXT,
    video_url    TEXT,
    subject_id   BIGINT REFERENCES public.subjects(id),
    week         TEXT,
    full_content TEXT,
    objective    TEXT,
    resources    TEXT,
    uuid         TEXT,
    uuid_id      TEXT,
    status       TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT lessons_subject_id_title_key UNIQUE (subject_id, title)
);

CREATE TABLE IF NOT EXISTS public.forum_posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name  TEXT NOT NULL,
    message    TEXT NOT NULL,
    lesson_id  BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.quizzes (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE,
    title     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id              BIGINT REFERENCES public.quizzes(id) ON DELETE CASCADE,
    question_text        TEXT NOT NULL,
    options              JSONB NOT NULL,
    correct_option_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_history (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  TEXT NOT NULL REFERENCES public.app_users(username) ON DELETE CASCADE,
    activity  TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 3. Avaliacoes
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.assessments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT REFERENCES public.subjects(id),
    type       TEXT NOT NULL,
    title      TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.assessment_questions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id        BIGINT REFERENCES public.assessments(id) ON DELETE CASCADE,
    question_text        TEXT NOT NULL,
    question_type        TEXT DEFAULT 'objective',
    options              JSONB,
    correct_option_index INTEGER DEFAULT 0,
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.student_assessments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username TEXT REFERENCES public.app_users(username),
    assessment_id BIGINT REFERENCES public.assessments(id),
    score         DOUBLE PRECISION,
    status        TEXT DEFAULT 'submitted',
    submitted_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.student_assessment_answers (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id         BIGINT REFERENCES public.student_assessments(id),
    question_id           BIGINT REFERENCES public.assessment_questions(id),
    selected_option_index INTEGER,
    answer_text           TEXT,
    answer_link           TEXT
);

-- -----------------------------------------------------------------------------
-- 4. Grade horaria e frequencia
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.schedules (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
    content    TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.attendance (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name   TEXT NOT NULL,
    student_number INTEGER,
    is_present     BOOLEAN DEFAULT TRUE,
    class_name     TEXT NOT NULL,
    subject_id     BIGINT REFERENCES public.subjects(id),
    date           DATE NOT NULL,
    professor_name TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT attendance_unique_v2 UNIQUE (student_name, class_name, subject_id, date)
);

CREATE TABLE IF NOT EXISTS public.weekly_schedule (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name     TEXT NOT NULL,
    day_of_week    TEXT NOT NULL,
    time_slot      TEXT NOT NULL,
    subject_name   TEXT NOT NULL,
    professor_name TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    class_id       BIGINT,
    CONSTRAINT weekly_schedule_unique UNIQUE (class_name, day_of_week, time_slot)
);

-- -----------------------------------------------------------------------------
-- 5. Automacao compartilhada com o portal (historico, planejamento, config)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.historico_aulas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- TEXTO no formato dd/mm/aaaa: e o formato gravado pelo bot do portal
    -- (iSeduc) e esperado por class_registry/compare_routes/duplicate_checker.
    data_aula     TEXT,
    horario       TEXT,
    turma         TEXT,
    disciplina    TEXT,
    status        TEXT,
    turma_id      TEXT,
    disciplina_id BIGINT,
    lesson_index  INTEGER,
    is_duplicate  BOOLEAN DEFAULT FALSE,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT historico_aulas_slot_unique UNIQUE (data_aula, horario, turma_id, disciplina_id)
);

CREATE TABLE IF NOT EXISTS public.planejamento (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turma                TEXT,
    disciplina           TEXT,
    data_planejada       DATE,
    horario              TEXT,
    numero_aula          INTEGER,
    turma_id             TEXT,
    disciplina_id        BIGINT,
    status               TEXT DEFAULT 'pendente',
    conteudo_abordado    TEXT,
    estrategia           TEXT,
    recursos_titulo      TEXT,
    recursos_link        TEXT,
    recursos_comentario  TEXT,
    atividade            TEXT,
    frequencia           TEXT,
    lesson_id            BIGINT,
    posicao_num          INTEGER,
    CONSTRAINT planejamento_slot_unique UNIQUE (data_planejada, horario, turma_id, disciplina_id)
);

CREATE TABLE IF NOT EXISTS public.master_config (
    key        TEXT PRIMARY KEY,
    value      JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 6. Migracoes idempotentes (colunas adicionadas depois em bancos legados)
-- -----------------------------------------------------------------------------
ALTER TABLE public.class_subjects ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.weekly_schedule ADD COLUMN IF NOT EXISTS class_id BIGINT;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS aliases JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS aliases_id BIGINT;
ALTER TABLE public.subjects ALTER COLUMN aliases_id TYPE BIGINT;
ALTER TABLE public.historico_aulas ADD COLUMN IF NOT EXISTS lesson_index INTEGER;
ALTER TABLE public.historico_aulas ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN DEFAULT FALSE;
ALTER TABLE public.planejamento ADD COLUMN IF NOT EXISTS lesson_id BIGINT;
ALTER TABLE public.planejamento ADD COLUMN IF NOT EXISTS posicao_num INTEGER;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS official_name TEXT;
ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS week TEXT;
ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS full_content TEXT;
ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS objective TEXT;
ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS resources TEXT;
ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS uuid TEXT;
ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS uuid_id TEXT;
ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS password_hash TEXT DEFAULT '';

-- Compat SysAVA NiceGUI (herdeiro): attendance + tabelas de push que o
-- enxuto não trazia (Streamlit gravava notas/qualitativos em JSON local).
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Presente';
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS class_id BIGINT;

CREATE TABLE IF NOT EXISTS public.student_grades (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username   TEXT NOT NULL,
    class_name      TEXT NOT NULL,
    subject         TEXT NOT NULL,
    trimester       INTEGER NOT NULL DEFAULT 1,
    nm1             DOUBLE PRECISION DEFAULT 0,
    nm2             DOUBLE PRECISION DEFAULT 0,
    nm3             DOUBLE PRECISION DEFAULT 0,
    participation   DOUBLE PRECISION DEFAULT 0,
    qualitative     DOUBLE PRECISION DEFAULT 0,
    final_grade     DOUBLE PRECISION DEFAULT 0,
    status          TEXT DEFAULT 'finalizado',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT student_grades_user_class_subject_trim_unique
        UNIQUE (user_username, class_name, subject, trimester)
);

CREATE TABLE IF NOT EXISTS public.qualitative_points (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username   TEXT NOT NULL,
    subject_id      BIGINT,
    points          DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes           TEXT DEFAULT '',
    date            TIMESTAMPTZ DEFAULT NOW(),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
    username      TEXT PRIMARY KEY,
    bio           TEXT DEFAULT '',
    avatar_url    TEXT DEFAULT '',
    notificacoes  JSONB,
    idioma        TEXT DEFAULT 'pt-BR',
    prefs         JSONB,
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 7. Indices
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_subjects_aliases_id ON public.subjects(aliases_id);
CREATE INDEX IF NOT EXISTS idx_subjects_aliases ON public.subjects USING gin (aliases);
CREATE INDEX IF NOT EXISTS idx_lessons_subject_id ON public.lessons(subject_id);
CREATE INDEX IF NOT EXISTS idx_forum_posts_lesson_id ON public.forum_posts(lesson_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_lesson_id ON public.quizzes(lesson_id);
CREATE INDEX IF NOT EXISTS idx_quiz_questions_quiz_id ON public.quiz_questions(quiz_id);
CREATE INDEX IF NOT EXISTS idx_user_history_username ON public.user_history(username);
CREATE INDEX IF NOT EXISTS idx_attendance_slot ON public.attendance(class_name, subject_id, date);
CREATE INDEX IF NOT EXISTS idx_historico_slot ON public.historico_aulas(turma_id, disciplina_id, data_aula);
CREATE INDEX IF NOT EXISTS idx_planejamento_slot ON public.planejamento(turma_id, disciplina_id, data_planejada);

-- -----------------------------------------------------------------------------
-- 8. Funcoes de resolucao de disciplinas (ver scripts/migracao_aliases_id_subjects.sql)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION normalize_subject_name(p text)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT regexp_replace(upper(unaccent(coalesce(p, ''))), '[^A-Z0-9]', '', 'g');
$$;

DROP FUNCTION IF EXISTS resolver_subject_id(text);
DROP FUNCTION IF EXISTS resolver_subject_exato(text);
DROP FUNCTION IF EXISTS resolver_subject_raiz(integer);

CREATE OR REPLACE FUNCTION resolver_subject_raiz(p_id bigint)
RETURNS bigint LANGUAGE sql STABLE AS $$
  WITH RECURSIVE up AS (
    SELECT id, aliases_id, 1 AS lvl FROM public.subjects WHERE id = p_id
    UNION ALL
    SELECT s.id, s.aliases_id, up.lvl + 1
    FROM public.subjects s
    JOIN up ON s.id = up.aliases_id
    WHERE up.lvl < 10
  )
  SELECT id FROM up WHERE aliases_id IS NULL ORDER BY lvl DESC LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION resolver_subject_exato(p_nome text)
RETURNS bigint LANGUAGE plpgsql STABLE AS $$
DECLARE
  v_norm text := normalize_subject_name(p_nome);
  v_id   bigint;
BEGIN
  IF v_norm = '' THEN RETURN NULL; END IF;
  SELECT id INTO v_id FROM public.subjects WHERE normalize_subject_name(name) = v_norm LIMIT 1;
  IF v_id IS NULL THEN
    SELECT s.id INTO v_id
      FROM public.subjects s
     WHERE EXISTS (
       SELECT 1 FROM jsonb_array_elements_text(s.aliases) a
        WHERE normalize_subject_name(a) = v_norm
     )
     LIMIT 1;
  END IF;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION resolver_subject_id(p_nome text)
RETURNS bigint LANGUAGE plpgsql STABLE AS $$
DECLARE v_id bigint := resolver_subject_exato(p_nome);
BEGIN
  IF v_id IS NULL THEN RETURN NULL; END IF;
  RETURN resolver_subject_raiz(v_id);
END;
$$;

-- -----------------------------------------------------------------------------
-- 9. Utilitario para o restore (reajusta as sequencias apos inserir IDs manuais)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.reset_identity_sequences()
RETURNS void LANGUAGE plpgsql AS $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.relname AS seq, t.relname AS tbl, a.attname AS col
    FROM pg_class c
    JOIN pg_depend d ON d.objid = c.oid
    JOIN pg_class t ON d.refobjid = t.oid
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
    WHERE c.relkind = 'S' AND t.relnamespace = 'public'::regnamespace
  LOOP
    EXECUTE format(
      'SELECT setval(%L, COALESCE((SELECT MAX(%I) FROM public.%I), 1))',
      r.seq, r.col, r.tbl
    );
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.reset_identity_sequences() TO anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 10. Acesso via chave anon (o app usa a anon key direto, sem Auth)
-- -----------------------------------------------------------------------------
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('ALTER TABLE public.%I DISABLE ROW LEVEL SECURITY', r.tablename);
  END LOOP;
END $$;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload schema';
