-- =============================================================================
-- PATCH: Supabase legado do SysAVA Streamlit (NOVO_BANCO_SCHEMA / 21 tabelas)
-- Compatibiliza o banco herdeiro com o push do SysAVA NiceGUI.
-- Idempotente: pode ser executado mais de uma vez no SQL Editor.
--
-- Executar NO PROJETO LEGADO (o do Streamlit), não no projeto novo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. attendance: colunas usadas pelo NiceGUI (status / class_id)
-- -----------------------------------------------------------------------------
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Presente';
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS class_id BIGINT;

-- -----------------------------------------------------------------------------
-- 2. student_grades: formato NiceGUI (user_username) — Streamlit usa JSON local
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_grades (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username   TEXT NOT NULL,
    class_name      TEXT NOT NULL,
    subject         TEXT NOT NULL,
    trimester       INTEGER NOT NULL DEFAULT 1,
    nm1             DOUBLE PRECISION DEFAULT 0,
    nm2             DOUBLE PRECISION DEFAULT 0,
    nm3             DOUBLE PRECISION DEFAULT 0,
    participation   DOUBLE PRECISION DEFAULT 0,
    qualitative     DOUBLE PRECISION DEFAULT 0,
    final_grade     DOUBLE PRECISION DEFAULT 0,
    status          TEXT DEFAULT 'finalizado',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT student_grades_user_class_subject_trim_unique
        UNIQUE (user_username, class_name, subject, trimester)
);

-- -----------------------------------------------------------------------------
-- 3. qualitative_points: pontos de atividade (NiceGUI / futuro plugin)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.qualitative_points (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username   TEXT NOT NULL,
    subject_id      BIGINT,
    points          DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes           TEXT DEFAULT '',
    date            TIMESTAMPTZ DEFAULT NOW(),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_qualitative_user ON public.qualitative_points(user_username);
CREATE INDEX IF NOT EXISTS idx_qualitative_subject ON public.qualitative_points(subject_id);

-- -----------------------------------------------------------------------------
-- 4. user_profiles: perfil do usuário (push avulso do NiceGUI)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_profiles (
    username     TEXT PRIMARY KEY,
    bio          TEXT DEFAULT '',
    avatar_url   TEXT DEFAULT '',
    notificacoes JSONB,
    idioma       TEXT DEFAULT 'pt-BR',
    prefs        JSONB,
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 5. (Opcional) password_hash em app_users — para coexistir com NiceGUI
--    O NiceGUI aceita password (texto puro) e password_hash; esta coluna
--    permite migrar as senhas para hash sem quebrar o Streamlit.
-- -----------------------------------------------------------------------------
ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS password_hash TEXT DEFAULT '';

-- -----------------------------------------------------------------------------
-- 6. Grants / RLS (mesmo padrão do NOVO_BANCO_SCHEMA: RLS desligado, anon full)
-- -----------------------------------------------------------------------------
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT tablename FROM pg_tables
        WHERE schemaname = 'public'
          AND tablename IN ('attendance', 'student_grades', 'qualitative_points', 'user_profiles')
    LOOP
        EXECUTE format('ALTER TABLE public.%I DISABLE ROW LEVEL SECURITY', r.tablename);
    END LOOP;
END $$;

GRANT ALL ON public.attendance TO anon, authenticated, service_role;
GRANT ALL ON public.student_grades TO anon, authenticated, service_role;
GRANT ALL ON public.qualitative_points TO anon, authenticated, service_role;
GRANT ALL ON public.user_profiles TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload schema';
